# Visit https://github.com/lowlighter/metrics/blob/master/action.yml for full reference
name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 6 * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
      - name: 🦑 General
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@latest
        with:
          filename: general.svg
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: yyuueexxiinngg
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Hong_Kong
          output_action: gist
          committer_gist: ${{ secrets.GIST }}
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          plugin_languages: yes
          plugin_languages_analysis_timeout: 15
          plugin_languages_categories: markup, programming
          plugin_languages_colors: github
          plugin_languages_limit: 8
          plugin_languages_recent_categories: markup, programming
          plugin_languages_recent_days: 14
          plugin_languages_recent_load: 300
          plugin_languages_sections: most-used
          plugin_languages_threshold: 0%
          plugin_lines: yes
          plugin_traffic: yes
          
      - name: 🦑 Additional
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@latest
        with:
          filename: additional.svg
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          base: ""
          config_order: rss, music
          config_timezone: Asia/Hong_Kong
          output_action: gist
          committer_gist: ${{ secrets.GIST }}
          plugin_rss: yes
          plugin_rss_limit: 4
          plugin_rss_source: https://blog.hoshi.tech/feed
          plugin_music: yes
          plugin_music_limit: 4
          plugin_music_mode: playlist
          plugin_music_playlist: ${{ secrets.MUSIC_PALYLIST }}
          plugin_music_time_range: short
          plugin_music_top_type: tracks
          plugin_music_user: ${{ secrets.MUSIC_USER }}
